[package]
name = "basic_control_flow"
version = "0.1.0"
authors = ["douglas sangster <douglas@an-email.home>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
